### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by Bejta** [ej222pj/1DV450_ej222pj#1]
I klassen AdminsController det finns linje:
`before_action :check_user, only: [:show, :destroy]`
Jag har för mig att det skulle funka som det är tänkt bara om man skriver:
`before_action :check_user`
eftersom `show` och `destroy` är enda metoder som finns i controller.

**Comment by Bejta** [comment]
Gäller samma för ApikeysController, `only:` gör en vit lista men inkluderar alla metoder i klassen.

**Comment by ej222pj** [comment]
Tänkte jag inte på. Kommer ändra på det

**Comment by 1dv450** [comment]
:+1:
