### ISSUE TITLE
Förslag

### ISSUE THREAD

**Issue by Bejta** [ej222pj/1DV450_ej222pj#2]
Adminvyn "show" på linje 7 står det:

`<% if users.id != 1%>`

Vad händer om det finns fler än en användare med admin rättigheterna?
Visst, det står i kravspecifikation:

> Applikationen ska ha ett administratörskonto (OK att hårdkoda in dennes inloggningsuppgifter)

så min fråga är bara om du har tänkt på det. Mitt förslag är ett fält  ( t.ex. "admin") i tabellen User av typen boolean och default värde false. Sen en funktion is_admin direkt i application controller.
Använda funktionen vidare är trivialt.

**Comment by ej222pj** [comment]
Har inte tänkte på det, får se hur jag gör, om jag använder fler än 1 admin. Men tack för förslaget:)
